"""
sar_generator.py — Builds SAR narrative text from ML-flagged case data.

Instead of hardcoded narratives, this generates a structured SAR report
based on the actual ML predictions and transaction data.
"""

import random
import string
from datetime import datetime

import ml_engine


def generate_sar(case_id: str) -> dict:
    """Generate a full SAR package for a given ML case ID."""
    cases = ml_engine.get_cases()
    case = next((c for c in cases if c["id"] == case_id), None)

    if case is None:
        return {"error": f"Case {case_id} not found"}

    ml_stats = ml_engine.get_case_ml_stats(case_id)

    sar_id = f"SAR-{datetime.now().year}-{random.randint(1800, 9999)}"

    # Build the narrative
    narrative = _build_narrative(case, sar_id)

    # Determine triggered rules from typology and risk
    rules = _infer_rules(case)

    return {
        "sarId": sar_id,
        "subject": case["customer"],
        "customerId": f"ID-{''.join(random.choices(string.digits, k=6))}",
        "period": f"Reporting Period ending {case['opened']}",
        "totalValue": case["amount"],
        "narrative": narrative,
        "rules": rules,
        "riskScore": case["risk"],
        "mlStats": ml_stats,
        "source": "isolation_forest",
    }


def _build_narrative(case: dict, sar_id: str) -> str:
    """Generate a structured SAR narrative from case data."""

    risk_level = (
        "Critical" if case["risk"] >= 85
        else "High" if case["risk"] >= 70
        else "Medium" if case["risk"] >= 50
        else "Low"
    )

    typology_desc = {
        "Funnel Accounts": "consolidation of funds from multiple sources into a single account, consistent with known funnel account typologies",
        "Fan-Out Pattern": "rapid distribution of funds from a single source to multiple recipients, consistent with fan-out money laundering patterns",
        "High Value Anomaly": "unusually high-value transactions that deviate significantly from established baselines",
        "Anomaly Cluster": "a cluster of statistically anomalous transactions identified through machine learning analysis",
    }

    typology_text = typology_desc.get(
        case["typology"],
        "anomalous transaction patterns identified through automated monitoring"
    )

    ml_score_text = ""
    if "mlScore" in case:
        ml_score_text = f"\n\nML Anomaly Score: {case['mlScore']:.4f} (Isolation Forest model confidence)"

    narrative = f"""SUSPICIOUS ACTIVITY REPORT — NARRATIVE

SAR Reference: {sar_id}
Subject: {case['customer']}
Risk Level: {risk_level} ({case['risk']}/100)
Period: Reporting period ending {case['opened']}
Total Value of Suspicious Activity: {case['amount']}
Transactions Analysed: {case['txCount']}
Counterparties Involved: {case['counterparties']}
Jurisdictional Exposure: {case['jurisdiction']}

═══════════════════════════════════════════════════
DETECTION METHOD: Isolation Forest — Unsupervised ML
═══════════════════════════════════════════════════

This case was identified by the institution's Isolation Forest anomaly detection model. The model was trained on the full transaction dataset and flagged {case['txCount']} transactions associated with {case['customer']} as statistically anomalous.{ml_score_text}

Summary of Suspicion:

The institution's automated ML-based transaction monitoring system identified activity giving rise to suspicion of potential money laundering involving the above-referenced entity. The transaction pattern is consistent with {typology_text}.

The Isolation Forest model assigned a risk score of {case['risk']}/100, placing this case in the {risk_level} risk category. The entity's transactions were flagged based on deviation from normal transaction patterns across multiple features including transaction velocity, amount distributions, and counterparty diversity.

Detailed Description of Activity:

The entity's account processed {case['txCount']} transactions involving {case['counterparties']} distinct counterparties. Machine learning analysis identified the following anomalous characteristics:

• Transaction patterns deviate significantly from established baselines
• {case['typology']} typology detected with {risk_level.lower()} confidence
• {case['counterparties']} counterparties involved in the flagged activity
• Jurisdictional exposure: {case['jurisdiction']}

Risk Indicators Identified:

• ML anomaly detection flagged transactions as statistically unusual
• {case['typology']} pattern identified through unsupervised learning
• Risk score of {case['risk']}/100 exceeds the institution's alert threshold
• {_get_typology_indicators(case['typology'])}

Action Taken by the Institution:

The institution has placed enhanced monitoring on the entity's accounts. This Suspicious Activity Report has been generated by the automated SAR drafting system based on Isolation Forest ML model output. The case has been escalated for human review and is pending analyst confirmation before submission to the relevant regulatory authority.

═══════════════════════════════════════════════════
NOTE: This SAR was auto-generated by the ML pipeline.
Human review is required before regulatory submission.
═══════════════════════════════════════════════════"""

    return narrative


def _infer_rules(case: dict) -> list:
    """Infer which compliance rules were triggered based on case attributes."""
    rules = ["ML Anomaly Detection (ISO-FOREST)"]

    typology = case.get("typology", "")
    risk = case.get("risk", 0)

    if "Funnel" in typology:
        rules.extend(["Funnel Account Pattern (RULE-012)", "Counterparty Screening (RULE-022)"])
    if "Fan-Out" in typology:
        rules.extend(["Fan-Out Distribution (RULE-014)", "Rapid Disbursement (RULE-025)"])
    if "High Value" in typology:
        rules.append("High Value Transaction (RULE-005)")
    if risk >= 80:
        rules.append("High Risk Alert (RULE-001)")
    if case.get("jurisdiction", "") == "Multi":
        rules.append("Multi-Jurisdiction Exposure (RULE-031)")
    if case.get("counterparties", 0) >= 5:
        rules.append("Excessive Counterparties (RULE-022)")

    return rules


def _get_typology_indicators(typology: str) -> str:
    """Return additional risk indicators text based on typology."""
    indicators = {
        "Funnel Accounts": "Multiple sources funnelling into one account suggest consolidation of illicit proceeds",
        "Fan-Out Pattern": "Rapid distribution to multiple recipients suggests layering or smurfing activity",
        "High Value Anomaly": "Transaction values significantly exceed historical baselines for this entity type",
        "Anomaly Cluster": "Statistical clustering of unusual features across multiple transaction dimensions",
    }
    return indicators.get(typology, "Anomalous transaction behavior detected by ML model")
